package MKShoes.mkshoes_Backend.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
//Above elements are all auto generated by lombok
@Entity
@Table(name = "OrderItem")
public class orderItem {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int orderItemId;// PK auto generated

    @ManyToOne
    @JoinColumn(name = "orderId")
    private orders order;// Defines FK orderID

    @ManyToOne
    @JoinColumn(name = "productId")
    private products product;
    private int quantity;


}
